### ISSUE TITLE
how to define a NamedVector?

### ISSUE THREAD

**Issue by mkborregaard** [davidavdav/NamedArrays.jl#38]
I am trying to reduce a dimension from a matrix, but I cannot figure out the syntaxt to do it.
Example
```julia
# With normal arrays I would:
ar = rand(5,3)
ret = vec(sum(ar, 1))

# with named arrays I try:
nar = NamedArray(ar)
ret = NamedVector(sum(ar, 1)) # but this fails
```

I have tried all the combinations of parameters I could think of, including:
```julia
ret = sum(ar, 1)
ret = NamedVector(ret.array, (ret.dicts[2]), (ret.dimnames[2]))
```

Thanks!

**Comment by davidavdav** [comment]
```julia
NamedArray(rand(5))
```
produces a `NamedVector`.  For `sum()` you might want to consider
```julia
ar = NamedArray(rand(5,3))
ret = sum(ar, 1)
```

`vec(ret)` just returns a normal `Array`---I don't think there it is sensible to return a `NamedArray`.  

If you want to reduce the dimension, you can slice `ret[1,:]`.

**Comment by nalimilan** [comment]
> NamedArray(rand(5))
> 
> produces a NamedVector. For sum() you might want to consider
> 
> ar = NamedArray(rand(5,3))
> ret = sum(ar, 1)

`ret` is a one-column matrix, not a vector.


> vec(ret) just returns a normal Array---I don't think there it is sensible to return a NamedArray.

That wouldn't be absurd, as `vec` on sparse matrices returns a sparse vector already. There's also `reshape`, which should probably be overloaded so that it returns a `NamedArray` wrapping a reshaped `Array` instead of a `ReshapedArray` for efficiency and convenience.

**Comment by mkborregaard** [comment]
Agree with @nalimilan . For my use, the slicing `ret[1,:]` did the trick, thanks!

**Comment by mkborregaard** [comment]
Also, `NamedArray(rand(5))` produces a `NamedVector`, but one without names! Of course I can always `setnames!` but is there a constructor that lets me specify the names directly, like in `NamedArrays(rand(3,3), (["a","b","c"],["d","e","f"]))`? Could it be that it cannot recognise the second argument because it does not recognise it as a tuple?

**Comment by davidavdav** [comment]
Milan, 

I was not suggesting `sum(ar, 1)` would produce a vector.  

The problem I see with `vec()` and `reshape()` is how to choose array names.  We could just re-number them as default names, and we could make special cases for arrays with singleton dimensions, but otherwise reshaping will toss everything around and I don't see how sensible it is to keep the names.

**Comment by davidavdav** [comment]
Michael, 

The (default) names of `NamedArray(rand(5))` are `names(NamedArray(rand(5), 1)`, namely `String["1","2","3","4","5"]`.  

For specifying a 1-element tuple, you have to add a comma, as in 
```julia
n = NamedArray(rand(5), (["a", "b","c", "d", "e"],))
```
This is because Julia needs to separate the normal parenthesis-indicate-precedence meaning of `( )` from the tuple operator `()` I suppose. 

In Julia 0.5, you can also initialize with a one-element array of the names, `[["a", "b","c", "d", "e"]]`. Before 0.5, `[ ]` would be interpolating the array of names, rather than taking it as an element. 

But addressing your original request, that the constructor `NamedVector()` doesn't exist, I fixed that in the commit above through implementing `convert(::Type{NamedVector}, ...)` where the type matching remains a bit of magic to me.

**Comment by mkborregaard** [comment]
Wonderful, that solves my issue. Thanks a lot! Perhaps worth adding the 1-element tuple trick to the examples in readme.md?

**Comment by nalimilan** [comment]
> The problem I see with vec() and reshape() is how to choose array names. We could just re-number them as default names, and we could make special cases for arrays with singleton dimensions, but otherwise reshaping will toss everything around and I don't see how sensible it is to keep the names.

Indeed that would only work with singleton dimensions, but that's better than nothing. I can see two type-stable solutions: 1) raise an error in other cases than dropping singleton dimensions, or 2) accept all cases, but only keep names when possible.

**Comment by davidavdav** [comment]
>  I can see two type-stable solutions: 1) raise an error in other cases than dropping singleton dimensions, or 2) accept all cases, but only keep names when possible.

2) wouldn't really be type stable if you mean by dropping the names means reverting to the underlying array?

**Comment by nalimilan** [comment]
I mean creating a `NamedArray` without any names.
