### ISSUE TITLE
Convert method does not work with integer names

### ISSUE THREAD

**Issue by ckingdon95** [davidavdav/NamedArrays.jl#43]
The following causes a KeyError:

`using NamedArrays`
`x = NamedArray(Array([1 2; 3 4]), (["a","b"], [10,11]), (:rows,:cols))`
`convert(Array, x))`

As far as I can tell, this only happens if some of the labels are integers that do not match up with the natural index numbers of their dimension. (If [10,11] were replaced with [1,2] in the NamedArray above, then convert works).

I looked in convert.jl to see how it's implemented, but following works fine:

`x = NamedArray(Array([1 2; 3 4]), (["a","b"], [10,11]), (:rows,:cols))`
`x.array`

So I'm not sure why convert(Array, x) throws an error.

**Comment by zacsketches** [comment]
@ckingdon95 let me add to the conversation about the problem with `convert`.  I'm working through a Julia solution to the [Kaggle Titanic Dataset](https://www.kaggle.com/c/titanic/data) and running into a problem using a [Chi Squared Test from the HypothesisTests](http://hypothesistestsjl.readthedocs.io/en/stable/parametric/power_divergence_test.html?highlight=chisqtest) package.  The test requires an `Array` as input so I need to convert the `NamedArray` that I get back from the very convenient [FreqTables](https://github.com/nalimilan/FreqTables.jl) package into an `Array` before passing it.

When I run the following code it returns the error shown:

```
julia> train = readtable("train.csv");

julia> complete_cases!(train)
183×12 DataFrames.DataFrame

julia> ft2 = freqtable(train, :Embarked, :Survived)
3×2 Named Array{Int64,2}
Embarked ╲ Survived │  0   1
────────────────────┼───────
C                   │ 17  48
Q                   │  1   1
S                   │ 42  74

julia> ft2_array = convert(Array, ft2)
ERROR: KeyError: key 2 not found
 in getindex at /Users/zac/.julia/v0.5/DataStructures/src/ordered_dict.jl:350 [inlined]
 in indices(::DataStructures.OrderedDict{Int64,Int64}, ::Int64) at /Users/zac/.julia/v0.5/NamedArrays/src/index.jl:40
 in getindex at /Users/zac/.julia/v0.5/NamedArrays/src/index.jl:31 [inlined]
 in _getindex at ./multidimensional.jl:438 [inlined]
 in getindex at ./abstractarray.jl:752 [inlined]
 in copy!(::Array{Int64,2}, ::NamedArrays.NamedArray{Int64,2,Array{Int64,2},Tuple{DataStructures.OrderedDict{String,Int64},DataStructures.OrderedDict{Int64,Int64}}}) at ./multidimensional.jl:614
 in convert(::Type{Array}, ::NamedArrays.NamedArray{Int64,2,Array{Int64,2},Tuple{DataStructures.OrderedDict{String,Int64},DataStructures.OrderedDict{Int64,Int64}}}) at ./abstractarray.jl:709
```

However, this code does work:
```
julia> ft2_array = ft2.array
3×2 Array{Int64,2}:
 17  48
  1   1
 42  74
```

And for comparison on the same machine in the same environment this code works:
```
julia> using RDatasets

julia> iris = dataset("datasets", "iris");

julia> iris[:LongSepal] = iris[:SepalLength] .> 5.0;

julia> ft = freqtable(iris, :Species, :LongSepal)
3×2 Named Array{Int64,2}
Species ╲ LongSepal │ false   true
────────────────────┼─────────────
setosa              │    28     22
versicolor          │     3     47
virginica           │     1     49

julia> ft_array = convert(Array, ft)
3×2 Array{Int64,2}:
 28  22
  3  47
  1  49
```
### Confirming the error found by @ckingdon95 
When I convert the `:Survived` symbol to type `Array{Bool}` the error clears because the column names are no longer named `:0` before `:1`.  The following code works around the error, but **please fix this bug so we can star this Type up a little!**
```
julia> train[:Survived] = convert(Array{Bool}, train[:Survived]);

julia> ft3 = freqtable(train, :Embarked, :Survived);

julia> ft3_array = convert(Array, ft3)
3×2 Array{Int64,2}:
 17  48
  1   1
 42  74
```

**Comment by nalimilan** [comment]
FWIW, HypothesisTests.jl should accept any `AbstractArray`, not just `Array`. Please also file an issue there about this.

**Comment by davidavdav** [comment]
Yep, this is a bug.  

NamedArrays is not really meant for non-base-1 integer indexing---I believe the newest Julia versions have support for that.  

NamedArrays is somewhat unusual in index interpretation, you can do both `n[i::Int]` and `n[key::KeyType]`.  For `KeyType == Int` this is ambiguous, so `NamedArrays` interprets an `Int` index as a key in this case, as you expected. 

The problem here can be traced to `copy!()`
```
y = Array(Float64, 2, 2)
copy!(y, x)
```
where Julia base code doesn't expect the indices to be offset.  I might want to fix this at this level.

**Comment by davidavdav** [comment]
OK, 

Ik think I could trace things further back to the use of `CartesianIndex`, which only had a fallback implementation through `Base.AbstractArray`.  

I should probably implement something like `Base.linearindexing(n::NamedArray)`, but that is another issue.
