### ISSUE TITLE
size(n,1) NamedArray subset from a 2d NamedArray has broken name indexing

### ISSUE THREAD

**Issue by phaverty** [davidavdav/NamedArrays.jl#7]
I'm very happy to have found this package.  Having names on things prevents so many awful ordering bugs.  Indexing by name is one of the best features of R. Thanks for bringing this to Julia!

It seems that when you subset a single column from a NamedArray matrix you get a NamedArray with broken name indexing. Also, why do the Dicts change type from Dict{ASCIIString,Int64} to Dict{Any,Int64} ?  This doesn't seem to affect function, but I'm guessing that was unintended.

x = NamedArray([1 2 3; 4 5 6; 7 8 9], (["A","B","C"],["bob","joe","fred"]),("X","Y"))
x["A",:] # works
y = x[:,1:2]
y["A",:] # works
z = x[:,1]
z["A",:] # broken
foo = NamedArray([1,2,3],(["A","B","C"],),("FOO",))
foo["A"] # works

**Comment by davidavdav** [comment]
Hello,

Thank, I thing names in R is a great thing, too, that's why I worked hard to get it going in Julia. 

First, I agree that in slicing, the dictionary type should not change.  This is probably a result of weird Julia behaviour w.r.t. the type in comprehension.  I think there are issue out there, but apparently it is hard to fix.  I could try harder to maintain the key type. 
```julia
z = x[:,1]
z["A",:] # broken
```
I don't agree here---`z = x[:,1]` silently drops a dimension, this is behaviour compatible with standard Julia array slicing rules.  However,
```julia
z=x["A"] # broken
```
is still broken.  I'd have to look into this. It looks like the broken key type of the dict (Any vs ASCIIString) is causing the index not to find the right getindex function.  Thanks for finding this bug,

**Comment by phaverty** [comment]
Great, thanks for looking into that. Sorry I was unclear. Dropping the dimension is correct and desirable. The failure of the Dict on the new 1d array was the only problem. 

Typed with thumbs.

**Comment by davidavdav** [comment]
Github didn't close automatically.  I should say "fixes #7" in the future.

**Comment by davidavdav** [comment]
Github didn't close automatically.  I should say "fixes #7" in the future.
